### ISSUE TITLE
What should we do if we use input element in container?

### ISSUE THREAD

**Issue by hkaraoglu** [supraniti/Lean-Mean-Drag-and-Drop#10]
What should we do when we use input element in draggable item? Below example, I added input element into one of draggable grid items, Then I want to click this input, but it is not clickable. Because your draggable item js code prevents me to click on it. How can I overcome this?

<img width="712" alt="screen shot 2017-07-29 at 22 32 24" src="https://user-images.githubusercontent.com/7407515/28747661-0ff04d8e-74ad-11e7-87a8-9aea280064e9.png">
 

https://supraniti.github.io/Lean-Mean-Drag-and-Drop/

**Comment by supraniti** [comment]
add class 'lmdd-block' to the div element
