### ISSUE TITLE
Alter / remove ghost animation ?

### ISSUE THREAD

**Issue by maelpetit** [supraniti/Lean-Mean-Drag-and-Drop#16]
Hi :)
Is there any way to alter or remove the ghost animation of the element being dragged ?

Thanks !

**Comment by supraniti** [comment]
With css:
Selector for the "shadow" or "placeholder" element
.lmdd-shadow

Selector for the "mirror" element
.lmdd-mirror

**Comment by maelpetit** [comment]
Thanks for your answer !!

However I cant figure out how to do what i want :/
I dont want the animation while i am dragging the item over containers, i just want it to pop in place, no transition animation.

Thanks also for lmdd :)

**Comment by supraniti** [comment]
You can control the transition duration with the following css:
(the default is 0.7s which is a little too much... 0.3s is more suttle, and
0 will eliminate all transition)

.visible-layer,
.visible-layer * {
    transition: all 0.3s !important;
}

best regards :)

**Comment by maelpetit** [comment]
Thanks again ! Thats exaclty what i needed :)

**Comment by maelpetit** [comment]
Just one more thing and then i hope i wont bother you anymore : Is there any way to nest 2 lmdd instances ? I would like to have a similar interface as the Vue example on your website but be able to drag and drop the columns to rearrange them left or right. Here is my attempt  (i tried to remove as much code as possible): 

```
<div id="vue-example" class="padded">
                <div id="drag-scope" class="container">
                <div class="column">
                        <div class="title handle">Tasks</div>
                        <todo-container class="regular green lighten-5" v-bind:data="todos.regular">
                            <todo-item v-for="(todo, index) in todos.regular" v-bind:data="todo" v-on:remove="todos.regular.splice(index, 1)"/>
                        </todo-container>
                </div>
                <div class="column">
                        <div class="title handle">High Priority</div>
                        <todo-container class="priority red lighten-4" v-bind:data="todos.priority">
                            <todo-item v-for="(todo, index) in todos.priority" v-bind:data="todo" v-on:remove="todos.priority.splice(index, 1)"/>
                        </todo-container>
                </div>
                [...]
            </div>
            <pre>{{$data}}</pre>
        </div>
        <script>
            Vue.component('todo-container', {
                template: '<div class="todo-container"><slot></slot></div>',
                props: ['data']
            });
            Vue.component('todo-item', {
                template:
                        '<div class="z-depth-3 todo-item">'+
                            '<a class="remove" v-on:click="$emit(\'remove\')"><i class="mdi mdi-close icon"/></a>'+
                            '<div class="task">{{data}}</div>'+
                        '</div>',
                props: ['data']
            });
            var vueExample = new Vue({
                el: '#vue-example',
                data: {
                    [...]
                },
                mounted: function() {
                    lmdd.set(document.getElementById('drag-scope'), {
                        containerClass: 'container',
                        draggableItemClass: 'column',
                        handleClass: 'handle'
                    });
                    lmdd.set(document.getElementById('drag-scope'), {
                        containerClass: 'todo-container',
                        draggableItemClass: 'todo-item',
                        dataMode: true
                    });
                    this.$el.addEventListener('lmddend', this.handleDragEvent);
                }
               [...]
            });
```

**Comment by supraniti** [comment]
You dont need to have multiple lmdd instances...

Your markup should represent the following structure:
Row
    Column
        Task
        Task
    Column
        Task
    Column
        Task
        Task
Row
    Column
        Task
        Task
    Column
        Task

Row is a container (for the columns)
Column is a container (for tasks) AND a draggable
Task is a draggable

It should loom more or less like this:

<div class="container-class row-class" id="some-id">

<div class="container-class draggable-class column-class">

<div class="draggable-class task-class">
Task content
</div>

</div>

</div>

If i had to implement it in vue -
I would live that example as it is
Attach container class to the todo container component (which will enable
re-ordering the columns)
And thats about it...





בתאריך יום ו׳, 8 ביונ' 2018, 16:02, מאת maelpetit ‏<notifications@github.com

**Comment by maelpetit** [comment]
Thanks for your answer and patience ;)

**Comment by supraniti** [comment]
You are welcome :)

בתאריך יום ב׳, 11 ביונ' 2018, 10:33, מאת maelpetit ‏<
notifications@github.com>:
